### PR TITLE
Added support for FSharp kernels

### PR DESCRIPTION
**Pull request by MoFtZ**

### CODE REVIEW

**Comment by NatElkins** [comment]
Hey thanks!  This looks really interesting.  Does this compile for you as-is?  Right now it fails to build on my Ubuntu machine.  Specifically this line:

image

If I change the syntax to

```fsharp
        kernel.Invoke(!> buffer.Length, buffer.View,42)
```

it will compile, but then fails at runtime with the following error:

```
nathaniel@nelknet-linux:~/Projects/Scratchpad2$ dotnet run
Performing operations on CPUAccelerator [WarpSize: 1, MaxNumThreadsPerGroup: 12, MemorySize: 9223372036854775807]
Unhandled exception. System.NotSupportedException: Class type 'Program+kernel@22' is not supported
   at ILGPU.IR.Types.IRTypeContext.CreateType(Type type, MemoryAddressSpace addressSpace)
   at ILGPU.IR.IRContext.CreateType(Type type, MemoryAddressSpace addressSpace)
   at ILGPU.IR.Construction.IRBuilder.CreateType(Type type, MemoryAddressSpace addressSpace)
   at ILGPU.IR.Construction.IRBuilder.CreateType(Type type)
   at ILGPU.Frontend.CodeGenerator.SetupVariables()
   at ILGPU.Frontend.CodeGenerator..ctor(ILFrontend frontend, Builder methodBuilder, DisassembledMethod disassembledMethod, HashSet`1 detectedMethods)
   at ILGPU.Frontend.CodeGenerationPhase.GenerateCodeInternal(MethodBase method, Boolean isExternalRequest, HashSet`1 detectedMethods, Method& generatedMethod)
   at ILGPU.Frontend.ILFrontend.DoWork()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

I also made ILGPU only target `netstandard2.1`, although I don't think that would've affected this error.  Looks like it might be still compiled as a class.

**Comment by MoFtZ** [comment]
It uses T4 templates to generate code. Not sure how to run the templates in Ubuntu, so I've added the generated files.

**Comment by NatElkins** [comment]
@MoFtZ Sorry this took me so long to come back to.  I just gave it a try with the files committed (it appears I can't get T4 to run on Ubuntu) and it works!

Would you consider making a PR of ILGPU.FSharp to the ILGPU repo?

**Comment by MoFtZ** [comment]
hi @NatElkins, unfortunately no, I don't think it's appropriate to get the ILGPU.FSharp changes merged into the main ILGPU repository. F# support for ILGPU should probably be made in a separate repository as it pulls in F#-only dependencies.

As mentioned in https://github.com/m4rs-mt/ILGPU.Samples/issues/7, the proper solution is for ILGPU to be updated to support class types. Once that is done, the only benefit of the ILGPU.FSharp changes would be to provide a more F#-friendly syntax.

**Comment by MoFtZ** [comment]
@NatElkins ILGPU v0.9.0-beta1 now has support for using non-capturing lambdas as the entry point kernel. This change also covers F#, so you don't need the latest F# compiler.

**Pull request closed without merging**
